name: Build

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: brew install ninja

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure
        run: |
          cmake --preset debug

      - name: Build
        run: |
          cmake --build --preset debug